Improve cross compilation
goblint/GobPie pull request #47
Opened 2023-02-04 16:23 UTC by FeldrinH

This PR improves cross compilation of the project. Cross compiling is desireable, because on Windows IntelliJ and some other IDE-s are very flaky when trying to edit a project in the WSL filesystem.

Changes:
* Added some useful scripts to compile and run GobPie in both Window and Linux 
* Fixed an issue with compiled jar only bundling required native JS engine dependencies for the same OS, making it not fully cross-platform.

2023-02-06 13:37 UTC, karoliineh requested changes
Scripts seem to work, but I am not sure if the project root is the best place for them. As they are still VScode specific, maybe move them into the `vscode` folder where the `installGobpie.sh` script is located as well?

2023-02-06 13:37 UTC, karoliineh commented on build_and_test.bat
> +call mvn package
```suggestion
call mvn clean package
```

2023-02-06 13:37 UTC, karoliineh commented on build_and_test.sh
> +mvn package
```suggestion
mvn clean package
```

2023-02-06 13:37 UTC, karoliineh commented on install_and_test.sh
> +eval $(opam env --switch=/home/user/goblint/analyzer --set-switch)
The switch path is awfully specific. Should have at least a comment `# Replace with your ..` like below. But that still makes tracking the scripts with git painful, as everyone has their own path there.

2023-02-06 13:37 UTC, karoliineh commented on build_and_test.sh
> +mvn package
This fixes most of the Maven warnings about overlapping classes, but there is still one remaining that is caused by the added `graphviz-java-all-j2v8` dependency.

2023-02-06 14:37 UTC, FeldrinH commented
I tried to move the environment-specific paths into a .env file. It works on my computer, but I am not very good with shell scripting, so it might do something weird with different setups.

2023-02-06 14:57 UTC, karoliineh commented
> I tried to move the environment-specific paths into a .env file. It works on my computer, but I am not very good with shell scripting, so it might do something weird with different setups.

Works for me, though.

2023-02-06 15:02 UTC, karoliineh reviewed
Please also add the script files to `.vscodeignore` so that they are not bundled with the extension.

2023-02-06 15:55 UTC, FeldrinH commented
Done. I added all .sh and .bat scripts to .vscodeignore

2023-02-07 12:24 UTC, karoliineh approved these changes

2023-02-07 13:03 UTC, sim642 approved these changes

2023-02-08 10:06 UTC, merged